#!/bin/sh

install() {
  rm -f $1
  ln -s .dotfiles/$1
}

cd
if [ -d Library ]; then
  cd Library
  rm -rf Scripts
  ln -s ../.dotfiles/Library/Scripts
  cd Preferences
  ln -s ../../.dotfiles/Library/Preferences/com.googlecode.iterm2.plist
  ln -s ../../.dotfiles/Library/Preferences/com.ugolandini.Pomodoro.plist
  cd ..
fi
install .gitconfig
install .inputrc
install .irbrc
install .tmux.conf
install .vim
install .vimrc
install .zshenv
install .zshrc
